require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/teas', type: :request do
  describe 'happy paths' do
    it '#create' do
      info = { "title": 'black tea',
               "description": 'super hype goodness',
               "brew_details": 'Steep in 45 ml of medium high temp water for 15 minutes' }

      headers = { 'CONTENT_TYPE' => 'application/json' }

      post '/api/v1/teas', headers: headers, params: JSON.generate(info)

      expect(response).to be_successful

      parsed_body = JSON.parse(response.body, symbolize_names: true)

      expect(parsed_body).to have_key(:data)
      expect(parsed_body[:data]).to be_a Hash

      tea = parsed_body[:data]

      expect(tea).to have_key :id
      expect(tea[:id]).to be_a String
      expect(tea).to have_key :type
      expect(tea[:type]).to eq('tea')

      expect(tea).to have_key :attributes

      expect(tea[:attributes]).to have_key :title
      expect(tea[:attributes][:title]).to be_a String
      expect(tea[:attributes]).to have_key :description
      expect(tea[:attributes][:description]).to be_a String
      expect(tea[:attributes]).to have_key :brew_details
      expect(tea[:attributes][:brew_details]).to be_a String
    end
    it '#index' do
      tea1 = Tea.create!(title: 'Black Tea', description: 'super hype goodness', brew_details: 'Do the thing')
      tea2 = Tea.create!(title: 'Green Tea', description: 'sorta hype goodness', brew_details: 'Do the other thing')

      get '/api/v1/teas'

      expect(response).to be_successful

      parsed_body = JSON.parse(response.body, symbolize_names: true)

      expect(parsed_body).to have_key(:data)
      expect(parsed_body[:data]).to be_a Array
      expect(parsed_body[:data].length).to eq 2

      tea = parsed_body[:data][0]

      expect(tea).to have_key :attributes

      expect(tea[:attributes]).to have_key :title
      expect(tea[:attributes][:title]).to be_a String
      expect(tea[:attributes]).to have_key :description
      expect(tea[:attributes][:description]).to be_a String
      expect(tea[:attributes]).to have_key :brew_details
      expect(tea[:attributes][:brew_details]).to be_a String
    end
  end
end
